### ISSUE TITLE
Batch tester output - line numbers do not match test file

### ISSUE THREAD

**Issue by RLucy** [AGI-3/Aigo.Tools#2]
Added new test called line number test. Test questions are on line 3,10,12, and 15. But debug outputs line 1,2,3,and 4.

>8233 : M||1||"what is red?"||miss: everything  xtra: apple rhubarb tomato lasagna tulip daisy orchid carnation lily rose||everything||"apple rhubarb tomato lasagna tulip daisy orchid carnation lily rose"||||LineNumberTest 
>8233 : M||2||"where is the party?"||miss: here  xtra: ""I don't know""||here||"""I don't know"""||||LineNumberTest 
>8233 : M||3||"who won?"||miss: me  xtra: ""I don't know""||me||"""I don't know"""||||LineNumberTest 
>8233 : M||4||"is this the last test?"||miss: yes  xtra: ""I don't know""||yes||"""I don't know"""||||LineNumberTest 
>8238 : TS||0/4/0%  0s  LineNumberTest 

Priority level doesn't make a difference.

**Comment by mattkruse** [comment]
***Completed***
